name: Go Build and Test

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - '*'
    paths-ignore:
      - '**.md'

jobs:
  build-linux:
    name: Build & Run Tests on Linux
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.23
      uses: actions/setup-go@v5
      with:
        go-version: ^1.23

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Building
      run: go build -v ./...

    - name: Testing
      run: go test -cover ./...

  build-windows:
    name: Build & Run Tests on Windows
    runs-on: windows-latest
    steps:

    - name: Set up Go 1.23
      uses: actions/setup-go@v5
      with:
        go-version: ^1.23

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Building
      run: go build -v ./...

    - name: Testing
      run: go test -cover ./...
