name: Official PHP Tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test-linux:
    name: Build & Run official PHP Tests on Linux
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.23
      uses: actions/setup-go@v5
      with:
        go-version: ^1.23

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Download php-src repository
      run: git clone https://github.com/php/php-src.git --depth 1

    - name: Building
      run: go build -v -o . ./...

    - name: Testing against official PHP Tests
      run: ./goPhpTester -v2 php-src/tests

  windows-linux:
    name: Build & Run official PHP Tests on Windows
    runs-on: windows-latest
    steps:

    - name: Set up Go 1.23
      uses: actions/setup-go@v5
      with:
        go-version: ^1.23

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Download php-src repository
      run: git clone https://github.com/php/php-src.git --depth 1

    - name: Building
      run: go build -v -o . ./...

    - name: Testing against official PHP Tests
      run: .\goPhpTester.exe -v2 php-src\tests